name: Rebase dev onto main after PR merge

on:
  pull_request:
    types: [closed]
    branches:
      - main


jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Checkout dev branch
        run: git checkout dev

      - name: Rebase dev onto main
        run: |
          git fetch origin
          git rebase origin/main

      - name: Force push rebased dev to remote
        run: |
          git push origin dev --force-with-lease